import '../styles/globals.css'
import { SessionProvider } from 'next-auth/react';

import Head from 'next/head';
import Header from '../sharedComponents/Header';

import MarmotProvider from '../sharedComponents/MarmotProvider/marmotProvider';

const MyApp = ({ 
  Component, 
  pageProps : { session, ...pageProps} 
}) => {

  return (
  <div>
    <main className="pt-5 text-center" id='main-content'>
      <Head>
        <title>Marmot Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionProvider>
        <MarmotProvider>
          <Header {...pageProps}/>
          <Component {...pageProps} />
        </MarmotProvider>
      </SessionProvider>
      </main>
  </div>
  )
}

export default MyApp
