import '../styles/globals.css'
import { SessionProvider } from 'next-auth/react';

import Head from 'next/head';
import Header from '../sharedComponents/Header';

import MarmotProvider from '../sharedComponents/MarmotProvider/marmotProvider';

const MyApp = ({ Component, pageProps, session }) => {

  return (
  <div>
      <Head>
        <title>Marmot Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <SessionProvider session={session}>
      <MarmotProvider>
        <Header/>
        <Component {...pageProps} />
      </MarmotProvider>
    </SessionProvider>
  </div>
  )
}


export default MyApp
